import { DomainError, assertCop, assertPermission, assertTransition, buildAttentionQueue, buildRecentActivity, calculateDashboard, calculateTax, calculateLineAmounts, calculateLineTotal, groupExpenseByPeriod, groupExpenseByTag, groupExpenseByWork, groupOrderItems, hasPermission, normalizeItemName, orderTypeFor, sumLines, validateShares, type Actor, type AuditEvent, type Expense, type ExpenseShare, type ItemLine, type Order, type OrderStatus, type PettyCash, type Requisition, type RequisitionChannel, type RequisitionType } from "../domain";
import type { AuditRepository, RequestContext, ServiceDependencies, TransactionRepositories } from "./contracts";

export interface CreateRequisitionInput { type: RequisitionType; workId: string; requiredDate: string; channel: RequisitionChannel; requesterId?: string; externalRequester?: { name: string; phone?: string }; destination?: string; observations?: string; items: ItemLine[]; publicCode?: string; publicLinkToken?: string; kapsoEventId?: string; }
/** approverId is intentionally absent: the current tag configuration owns routing. */
export interface ReviewInput { tagId: string; items: ItemLine[]; }
export interface PettyCashInput { workId: string; date: string; concept: string; tagId: string; amount: number; attachmentUrl?: string; }

export class ProcurementService {
  constructor(private readonly deps: ServiceDependencies) {}
  private now(): Date { return this.deps.clock.now(); }
  private origin(context: RequestContext): "web" | "mcp" | "kapso" { return context.origin ?? "web"; }
  private authOrigin(context: RequestContext): "web" | "mcp" { return this.origin(context) === "mcp" ? "mcp" : "web"; }
  private transaction<T>(lockKey: string | undefined, work: Parameters<ServiceDependencies["transactions"]["transaction"]>[1]): Promise<T> { return this.deps.transactions.transaction(lockKey, work) as Promise<T>; }
  private actor(context: RequestContext): Actor { if (!context.actor) throw new DomainError("UNAUTHENTICATED", "Debe autenticarse"); return context.actor; }
  private async requisition(id: string): Promise<Requisition> { const requisition = await this.deps.requisitions.get(id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); return requisition; }
  private async audit(entity: string, entityId: string, event: string, actor: Actor, data?: Record<string, unknown>, origin: "web" | "mcp" | "kapso" = "web", repository: AuditRepository = this.deps.audit): Promise<void> { const actorId = actor.id === "kapso" || actor.id === "public" ? undefined : actor.id; await repository.append({ entity, entityId, event, actorId, at: this.now(), data, origin }); }
  private async transition(requisition: Requisition, to: Requisition["status"], actor: Actor, event: string, comment?: string, origin: "web" | "mcp" | "kapso" = "web", auditRepository?: AuditRepository): Promise<void> { const from = requisition.status; assertTransition(from, to, comment); requisition.status = to; await this.audit("requisicion", requisition.id, event, actor, { from, to, ...(comment ? { comment } : {}) }, origin, auditRepository); }
  private async notifyRequester(requisition: Requisition, template: string, tx: TransactionRepositories): Promise<void> { const channel = requisition.channel === "web" ? "interno" : "whatsapp"; if (requisition.requesterId) await tx.notifications.enqueue({ userId: requisition.requesterId, channel, template, payload: { requisitionId: requisition.id, consecutive: requisition.consecutive } }); else if (requisition.externalRequester?.phone) await tx.notifications.enqueue({ phone: requisition.externalRequester.phone, channel: "whatsapp", template, payload: { requisitionId: requisition.id, consecutive: requisition.consecutive } }); }
  private async materializeProposals(lines: readonly ItemLine[], actor: Actor, origin: "web" | "mcp" | "kapso", tx: TransactionRepositories): Promise<ItemLine[]> { const result: ItemLine[] = []; for (const line of lines) { if (!line.itemId && !line.description?.trim()) throw new DomainError("INVALID_INPUT", "Cada línea requiere un ítem o una propuesta"); if (line.itemId) { result.push({ ...line }); continue; } const description = line.description!.trim(); if (!normalizeItemName(description)) throw new DomainError("INVALID_INPUT", "La propuesta debe contener letras o números"); const proposal = await tx.items.propose(description, line.unit, /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(actor.id) ? actor.id : undefined); if (proposal.created) await this.audit("item", proposal.id, "propuesto", actor, { source: origin }, origin, tx.audit); result.push({ ...line, itemId: proposal.id, description }); } return result; }

  async create(input: CreateRequisitionInput, context: RequestContext): Promise<Requisition> {
    const origin = this.origin(context);
    const isExternalChannel = input.channel === "publico" || input.channel === "whatsapp";
    if (input.channel === "publico") { if (!input.publicLinkToken || !input.publicCode || !(await this.deps.publicAccess.verify(input.workId, input.publicLinkToken, input.publicCode))) throw new DomainError("PUBLIC_ACCESS_DENIED", "Enlace o código público inválido"); }
    else if (input.channel === "whatsapp") { if (origin !== "kapso" || !input.kapsoEventId?.trim()) throw new DomainError("FORBIDDEN", "WhatsApp solo acepta eventos Kapso verificados"); }
    else assertPermission(this.actor(context).roles, "requisition:create", this.authOrigin(context));
    if (!input.workId || !input.requiredDate || !input.items.length) throw new DomainError("INVALID_INPUT", "Obra, fecha e ítems son obligatorios"); sumLines(input.items);
    const externalPhone = input.externalRequester?.phone?.replace(/[\s()\-]/g, "");
    if (isExternalChannel && (!input.externalRequester?.name?.trim() || !externalPhone || !/^\+?[1-9]\d{6,14}$/.test(externalPhone))) throw new DomainError("INVALID_INPUT", "Nombre y teléfono externo válidos son obligatorios"); if (!isExternalChannel && input.externalRequester) throw new DomainError("INVALID_INPUT", "Solicitante externo no permitido en canal web");
    const actor = context.actor ?? { id: input.channel === "whatsapp" ? "kapso" : "public", roles: [] }, elevated = actor.roles.includes("revisor") || actor.roles.includes("admin_mizar") || actor.roles.includes("admin_sixteam");
    if (!isExternalChannel && input.requesterId && input.requesterId !== actor.id && !elevated) throw new DomainError("FORBIDDEN", "Un solicitante solo puede crear para sí mismo");
    const requesterId = isExternalChannel ? undefined : input.requesterId ?? actor.id, year = Number(input.requiredDate.slice(0, 4)); if (!Number.isInteger(year)) throw new DomainError("INVALID_INPUT", "Fecha requerida inválida");
    return this.transaction(undefined, async (tx) => { const requisition: Requisition = { id: this.deps.ids.next(), consecutive: await tx.consecutives.take("REQ", year), type: input.type, workId: input.workId, requesterId, externalRequester: input.externalRequester ? { ...input.externalRequester, phone: externalPhone } : undefined, channel: input.channel, requiredDate: input.requiredDate, destination: input.destination, observations: input.observations, kapsoEventId: input.channel === "whatsapp" ? input.kapsoEventId : undefined, items: await this.materializeProposals(input.items, actor, origin, tx), status: "enviada" }; await tx.requisitions.save(requisition); await this.audit("requisicion", requisition.id, "creada", actor, { channel: input.channel }, origin, tx.audit); if (isExternalChannel) await this.notifyRequester(requisition, "requisicion_recibida", tx); return requisition; });
  }
  async startReview(id: string, context: RequestContext): Promise<Requisition> { const actor = this.actor(context); assertPermission(actor.roles, "requisition:review", this.authOrigin(context)); return this.transaction(`requisition:${id}`, async (tx) => { const requisition = await tx.requisitions.get(id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); await this.transition(requisition, "en_revision", actor, "entrada_revision", undefined, this.origin(context), tx.audit); await tx.requisitions.save(requisition); return requisition; }); }
  async proposeItem(requisitionId: string, description: string, context: RequestContext): Promise<Requisition> { const actor = this.actor(context); assertPermission(actor.roles, "requisition:create", this.authOrigin(context)); if (!description.trim()) throw new DomainError("INVALID_INPUT", "Descripción obligatoria"); return this.transaction(`requisition:${requisitionId}`, async (tx) => { const requisition = await tx.requisitions.get(requisitionId); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); const reviewer = actor.roles.includes("revisor") || actor.roles.includes("admin_sixteam"); if (!reviewer && requisition.requesterId !== actor.id) throw new DomainError("FORBIDDEN", "No puede modificar una requisición ajena"); const editable = reviewer ? ["en_revision", "devuelta"] : ["enviada"]; if (!editable.includes(requisition.status)) throw new DomainError("INVALID_STATE", "La requisición no admite nuevos ítems en este estado"); const [line] = await this.materializeProposals([{ id: this.deps.ids.next(), description: description.trim(), quantity: 1, unit: "unidad", unitBase: 0, unitIva: 0 }], actor, this.origin(context), tx); requisition.items.push(line); await tx.requisitions.save(requisition); await this.audit("requisicion", requisition.id, "item_propuesto", actor, { itemId: line.itemId }, this.origin(context), tx.audit); return requisition; }); }
  async review(id: string, input: ReviewInput, context: RequestContext): Promise<Requisition> {
    const actor = this.actor(context); assertPermission(actor.roles, "requisition:review", this.authOrigin(context)); if (!input.tagId) throw new DomainError("INVALID_INPUT", "Etiqueta obligatoria"); sumLines(input.items);
    return this.transaction(`requisition:${id}`, async (tx) => { const approverId = await tx.tags.getApproverId(input.tagId); if (!approverId) throw new DomainError("ROUTING_NOT_FOUND", "La etiqueta no tiene aprobador activo"); const requisition = await tx.requisitions.get(id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); if (requisition.status === "devuelta") await this.transition(requisition, "en_revision", actor, "retomada_revision", undefined, this.origin(context), tx.audit); if (requisition.status !== "en_revision") throw new DomainError("INVALID_STATE", "La requisición no está en revisión"); requisition.tagId = input.tagId; requisition.approverId = approverId; requisition.items = await this.materializeProposals(input.items, actor, this.origin(context), tx); await tx.requisitions.save(requisition); await this.audit("requisicion", id, "revisada", actor, { tagId: input.tagId, approverId }, this.origin(context), tx.audit); return requisition; });
  }
  async decline(id: string, reason: string, context: RequestContext): Promise<Requisition> { const actor = this.actor(context); assertPermission(actor.roles, "requisition:review", this.authOrigin(context)); return this.transaction(`requisition:${id}`, async (tx) => { const requisition = await tx.requisitions.get(id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); await this.transition(requisition, "declinada", actor, "declinada", reason.trim(), this.origin(context), tx.audit); requisition.declineReason = reason.trim(); await tx.requisitions.save(requisition); await this.notifyRequester(requisition, "requisicion_declinada", tx); return requisition; }); }
  async sendForApproval(id: string, context: RequestContext): Promise<Requisition> { const actor = this.actor(context); assertPermission(actor.roles, "requisition:review", this.authOrigin(context)); return this.transaction(`requisition:${id}`, async (tx) => { const requisition = await tx.requisitions.get(id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); const incompleteLines = requisition.items.some((line) => !line.finalSupplierId || calculateLineTotal(line) <= 0); if (!requisition.tagId || !requisition.approverId || !requisition.items.length || incompleteLines) throw new DomainError("REVIEW_INCOMPLETE", "Cada ítem requiere proveedor final y valor cotizado mayor a cero"); await this.transition(requisition, "en_aprobacion", actor, "enviada_aprobacion", undefined, this.origin(context), tx.audit); await tx.requisitions.save(requisition); await tx.notifications.enqueue({ userId: requisition.approverId, channel: "whatsapp", template: "pendiente_aprobador", payload: { requisitionId: requisition.id, consecutive: requisition.consecutive } }); return requisition; }); }
  async approve(id: string, context: RequestContext, multiSupplier = false): Promise<{ requisition: Requisition; orders: Order[]; expenses: Expense[] }> {
    const actor = this.actor(context); assertPermission(actor.roles, "requisition:approve", this.authOrigin(context));
    return this.deps.transactions.transaction(`requisition:${id}`, async (transactional) => {
      const requisition = await transactional.requisitions.get(id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada");
      if (requisition.approverId !== actor.id) throw new DomainError("NOT_ASSIGNED_APPROVER", "No es el aprobador asignado");
      if (requisition.status === "aprobada") { const [orders, expenses] = await Promise.all([transactional.orders.listByRequisition(id), transactional.expenses.listByReference(id)]); return { requisition, orders, expenses }; }
      if (multiSupplier && !(await transactional.features.isEnabled("ordenes_multi_proveedor"))) throw new DomainError("FEATURE_DISABLED", "La división por proveedor no está habilitada");
      const groups = groupOrderItems(requisition.items, multiSupplier, requisition.type), orderType = orderTypeFor(requisition.type), year = this.now().getFullYear(), orders: Order[] = [], expenses: Expense[] = [];
      await this.transition(requisition, "aprobada", actor, "aprobada", undefined, this.origin(context), transactional.audit);
      // El guardado de la requisición va ANTES de crear las órdenes: saveRequisition borra y
      // reinserta requisicion_items, y orden_items tiene una FK a esas filas. Si se guardara después
      // de crear las órdenes, el DELETE de los ítems chocaría con orden_items_requisicion_item_id_fkey
      // y ninguna aprobación se podría persistir contra Postgres (los ítems no cambian al aprobar,
      // solo el estado). Verificado contra la BD real.
      await transactional.requisitions.save(requisition);
      for (const [supplierId, lines] of groups) {
        const order: Order = { id: this.deps.ids.next(), consecutive: await transactional.consecutives.take(orderType, year), type: orderType, requisitionId: id, supplierId, itemIds: lines.map((line) => line.id), status: "generada" }; await transactional.orders.save(order); orders.push(order); await this.audit("orden", order.id, "generada", actor, { requisitionId: id, supplierId }, this.origin(context), transactional.audit);
        const base = lines.reduce((sum, line) => sum + calculateLineAmounts(line).base, 0), iva = lines.reduce((sum, line) => sum + calculateLineAmounts(line).iva, 0);
        const expense: Expense = { id: this.deps.ids.next(), workId: requisition.workId, origin: "requisicion", referenceId: order.id, tagId: requisition.tagId, supplierId, date: this.now().toISOString().slice(0, 10), base, iva, total: sumLines(lines), period: this.now().toISOString().slice(0, 7) }; await transactional.expenses.save(expense); expenses.push(expense); await this.audit("gasto", expense.id, "registrado", actor, { orderId: order.id, supplierId }, this.origin(context), transactional.audit);
      }
      await this.notifyRequester(requisition, "requisicion_aprobada", transactional); return { requisition, orders, expenses };
    });
  }
  async returnForCorrection(id: string, comment: string, context: RequestContext): Promise<Requisition> { const actor = this.actor(context); assertPermission(actor.roles, "requisition:return", this.authOrigin(context)); return this.transaction(`requisition:${id}`, async (tx) => { const requisition = await tx.requisitions.get(id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); if (requisition.approverId !== actor.id) throw new DomainError("NOT_ASSIGNED_APPROVER", "No es el aprobador asignado"); await this.transition(requisition, "devuelta", actor, "devuelta", comment.trim(), this.origin(context), tx.audit); requisition.returnReason = comment.trim(); await tx.requisitions.save(requisition); await this.notifyRequester(requisition, "requisicion_devuelta", tx); return requisition; }); }
  async updateOrderStatus(orderId: string, status: OrderStatus, context: RequestContext): Promise<Order> { const actor = this.actor(context); assertPermission(actor.roles, "order:update", this.authOrigin(context)); return this.transaction(`order:${orderId}`, async (tx) => { const order = await tx.orders.get(orderId); if (!order) throw new DomainError("NOT_FOUND", "Orden no encontrada"); if (order.status !== "generada" || !["cumplida", "no_cumplida", "no_necesario"].includes(status)) throw new DomainError("INVALID_TRANSITION", "Estado de orden inválido"); order.status = status; await tx.orders.save(order); await this.audit("orden", order.id, "estado_cumplimiento_actualizado", actor, { status }, this.origin(context), tx.audit); return order; }); }
  async redistribute(expenseId: string, total: number, shares: ExpenseShare[], context: RequestContext): Promise<void> { const actor = this.actor(context); assertPermission(actor.roles, "requisition:review", this.authOrigin(context)); if (shares.some((share) => share.expenseId !== expenseId)) throw new DomainError("INVALID_SHARE", "Todas las líneas deben pertenecer al gasto"); await this.transaction(`expense:${expenseId}`, async (tx) => { const expense = await tx.expenses.get(expenseId); if (!expense) throw new DomainError("NOT_FOUND", "Gasto no encontrado"); if (expense.total !== total) throw new DomainError("EXPENSE_TOTAL_MISMATCH", "El total del reparto no coincide con el gasto"); validateShares(expense.total, shares); await tx.expenses.saveShares(shares); await this.audit("gasto", expenseId, "repartido", actor, { total: expense.total }, this.origin(context), tx.audit); }); }
  async registerPettyCash(input: PettyCashInput, context: RequestContext): Promise<{ entry: PettyCash; expense: Expense }> { const actor = this.actor(context); assertPermission(actor.roles, "petty_cash:create", this.authOrigin(context)); if (!input.workId || !input.concept.trim() || !input.tagId) throw new DomainError("INVALID_INPUT", "Campos de caja menor obligatorios"); assertCop(input.amount, "Valor"); if (input.amount === 0) throw new DomainError("INVALID_MONEY", "El valor debe ser mayor a cero"); const entry: PettyCash = { id: this.deps.ids.next(), ...input, registeredBy: actor.id }; return this.transaction(undefined, async (tx) => { const expense = await tx.pettyCash.save(entry); await this.audit("caja_menor", entry.id, "registrada", actor, { expenseId: expense.id }, this.origin(context), tx.audit); await this.audit("gasto", expense.id, "registrado", actor, { origin: "caja_menor" }, this.origin(context), tx.audit); return { entry, expense }; }); }
  async listRequisitions(context: RequestContext): Promise<Requisition[]> { const actor = this.actor(context); if (!["requisition:read", "requisition:read:own", "requisition:read:assigned"].some((permission) => hasPermission(actor.roles, permission, this.authOrigin(context)))) throw new DomainError("FORBIDDEN", "No puede consultar requisiciones"); return this.deps.requisitions.listVisibleTo(actor); }
  async getRequisition(id: string, context: RequestContext): Promise<Requisition> { const visible = await this.listRequisitions(context), requisition = visible.find((entry) => entry.id === id); if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada"); return requisition; }
  async getRequisitionHistory(id: string, context: RequestContext): Promise<AuditEvent[]> { await this.getRequisition(id, context); return this.deps.audit.list("requisicion", id); }
  /**
   * Edita la cabecera de una requisición (ficha editable): fecha requerida, destino y observaciones.
   * Solo el revisor/admin (requisition:review) y solo mientras la requisición aún es editable
   * (enviada, en_revision o devuelta): una vez en aprobación, aprobada o declinada, la cabecera se
   * congela. NO toca ítems, obra ni tipo — eso alteraría la identidad o el gasto y va por el flujo
   * de revisión. Registra en auditoría qué cambió.
   */
  async updateRequisitionHeader(id: string, patch: { requiredDate?: string; destination?: string | null; observations?: string | null }, context: RequestContext): Promise<Requisition> {
    const actor = this.actor(context); assertPermission(actor.roles, "requisition:review", this.authOrigin(context));
    return this.transaction(`requisition:${id}`, async (tx) => {
      const requisition = await tx.requisitions.get(id);
      if (!requisition) throw new DomainError("NOT_FOUND", "Requisición no encontrada");
      if (!["enviada", "en_revision", "devuelta"].includes(requisition.status)) throw new DomainError("INVALID_STATE", "La requisición ya no admite cambios de cabecera en este estado");
      const changed: Record<string, unknown> = {};
      if (patch.requiredDate !== undefined && patch.requiredDate !== requisition.requiredDate) { requisition.requiredDate = patch.requiredDate; changed.requiredDate = patch.requiredDate; }
      if (patch.destination !== undefined) { const value = patch.destination?.trim() || undefined; if (value !== requisition.destination) { requisition.destination = value; changed.destination = value ?? null; } }
      if (patch.observations !== undefined) { const value = patch.observations?.trim() || undefined; if (value !== requisition.observations) { requisition.observations = value; changed.observations = value ?? null; } }
      if (Object.keys(changed).length === 0) return requisition;
      await tx.requisitions.save(requisition);
      await this.audit("requisicion", requisition.id, "cabecera_editada", actor, changed, this.origin(context), tx.audit);
      return requisition;
    });
  }
  async listOrders(context: RequestContext): Promise<Order[]> { const actor = this.actor(context); assertPermission(actor.roles, "order:read", this.authOrigin(context)); return this.deps.orders.listVisibleTo(actor); }
  async listExpenses(context: RequestContext): Promise<Expense[]> { const actor = this.actor(context); assertPermission(actor.roles, "expense:read", this.authOrigin(context)); return this.deps.expenses.listVisibleTo(actor); }
  async listPettyCash(context: RequestContext): Promise<PettyCash[]> { const actor = this.actor(context); assertPermission(actor.roles, "petty_cash:read", this.authOrigin(context)); return this.deps.pettyCash.list(); }
  async dashboard(period: string, context: RequestContext) {
    const actor = this.actor(context); assertPermission(actor.roles, "dashboard:read", this.authOrigin(context)); if (!/^\d{4}-\d{2}$/.test(period)) throw new DomainError("INVALID_INPUT", "Periodo inválido");
    const [requisitions, expenses, orders] = await Promise.all([this.deps.requisitions.listVisibleTo(actor), this.deps.expenses.listVisibleTo(actor), this.deps.orders.listVisibleTo(actor)]);
    const metrics = calculateDashboard(expenses, orders, requisitions.map((r) => r.status), period);
    metrics.inProcessValue = requisitions.filter((r) => r.status === "en_revision" || r.status === "en_aprobacion").reduce((sum, r) => sum + sumLines(r.items), 0);
    // RF-1102/RF-706/RF-1103: agregados adicionales sobre las mismas colecciones ya autorizadas por listVisibleTo,
    // igual que inProcessValue arriba; calculateDashboard no los produce para no romper su firma existente.
    metrics.attentionQueue = buildAttentionQueue(requisitions, orders, actor);
    metrics.recentActivity = buildRecentActivity(requisitions, orders, expenses);
    metrics.expenseByWork = groupExpenseByWork(expenses);
    metrics.expenseByTag = groupExpenseByTag(expenses);
    metrics.expenseByPeriod = groupExpenseByPeriod(expenses);
    return metrics;
  }
  calculateQuotedValue(base: number, ivaRate: number) { return calculateTax(base, ivaRate); }
  lineTotal(line: ItemLine) { return calculateLineTotal(line); }
}
