import { ArrowDownToLine, BarChart3, BriefcaseBusiness, CalendarDays, Check, FileCheck2, Plus, Receipt, Search } from 'lucide-react';
import { orders, works, formatMoney } from '../../lib/demo-data';
import { SectionTitle, Tone } from './screen-primitives';
import { AttachmentPicker } from './attachment-upload';
import type { Role } from '../../lib/demo-data';

export function OrdersScreen() { return <><SectionTitle eyebrow="Operación de compras" title="Órdenes" description="Cada aprobación genera su documento y estado de entrega." action={<button className="button button-secondary" type="button"><ArrowDownToLine size={15} /> Exportar</button>} /><div className="stats-strip"><div><span>Órdenes este mes</span><b>24</b></div><div><span>Pendientes de entrega</span><b className="text-amber">7</b></div><div><span>Valor comprometido</span><b>$ 31,6 M</b></div><div><span>Entrega media</span><b>3,2 días</b></div></div><section className="panel"><div className="panel-head"><div><h2>Órdenes generadas</h2><p className="panel-sub">Datos de demostración</p></div><div className="search-field small"><Search size={15} /><input aria-label="Buscar órdenes" placeholder="Buscar..." /></div></div><div className="table-wrap"><table><thead><tr><th>Orden</th><th>Proveedor</th><th>Obra</th><th>Estado</th><th className="align-right">Valor</th></tr></thead><tbody>{orders.map(order => <tr key={order.id}><td><b className="mono-id">{order.id}</b><small className="table-sub">{order.request}</small></td><td>{order.supplier}</td><td>{order.work}</td><td><Tone tone={order.state === 'Cumplida' ? 'success' : 'warning'} dot>{order.state}</Tone></td><td className="align-right money">{formatMoney(order.amount)}</td></tr>)}</tbody></table></div></section></>; }
export function ExpensesScreen({ role = 'Revisor' }: { role?: Role }) {
  const [open, setOpen] = React.useState(false);
  const [receiptFile, setReceiptFile] = React.useState<File | null>(null);
  const [feedback, setFeedback] = React.useState('');
  const canCreate = role === 'Revisor' || role === 'Administrador Sixteam';
  const save = () => {
    setFeedback(receiptFile ? 'Gasto demo guardado y recibo validado.' : 'Gasto demo guardado.');
  };
  return <>
    <SectionTitle eyebrow="Control financiero" title="Gastos y caja menor" description="El cuadro se alimenta de órdenes y movimientos de caja menor." action={<div className="title-actions"><button className="button button-secondary" type="button"><ArrowDownToLine size={15} /> Exportar Helisa</button>{canCreate && <button className="button button-dark" type="button" onClick={() => { setOpen(!open); setFeedback(''); }}><Plus size={16} /> Registrar caja menor</button>}</div>} />
    <div className="stats-grid expense-stats"><Metric label="Gasto del periodo" value="$ 42,8 M" icon={BarChart3} /><Metric label="Órdenes aprobadas" value="$ 40,9 M" icon={FileCheck2} /><Metric label="Caja menor" value="$ 1,9 M" icon={Receipt} /><Metric label="Presupuesto usado" value="72%" icon={BriefcaseBusiness} /></div>
    {open && canCreate && <div className="panel inline-form"><div className="panel-head"><h2>Registrar gasto de caja menor</h2><button className="icon-button" type="button" aria-label="Cerrar formulario" onClick={() => setOpen(false)}>×</button></div><div className="field-grid"><label className="field"><span>Obra *</span><select><option>{works[0]}</option></select></label><label className="field"><span>Concepto *</span><input placeholder="Ej. Tornillos y fijaciones" /></label><label className="field"><span>Valor *</span><input type="number" placeholder="$ 0" /></label></div><AttachmentPicker id="demo-petty-receipt" label="Recibo o soporte (opcional)" help="PDF, JPG, PNG o WebP · máximo 10 MB" file={receiptFile} onFile={setReceiptFile} onError={setFeedback} />{feedback && <p className={feedback.includes('guardado') ? 'field-success' : 'field-error'} role={feedback.includes('guardado') ? 'status' : 'alert'}>{feedback}</p>}<div className="form-footer"><span className="muted-copy">Demo sin persistencia</span><button className="button button-dark" type="button" onClick={save}><Check size={15} /> Guardar gasto</button></div></div>}
    <section className="panel expense-panel"><div className="panel-head"><div><div className="eyebrow">Agosto 2026 · demo</div><h2>Gastos por obra</h2></div><span className="printable"><CalendarDays size={14} /> 01 ago — 30 ago</span></div><div className="expense-overview"><div className="expense-chart"><div className="chart-bars"><i style={{height:'76%'}}/><i style={{height:'47%'}}/><i style={{height:'92%'}}/><i style={{height:'61%'}}/></div></div><div className="expense-total"><span>Total del periodo</span><strong>$ 42.802.000</strong><small>dato demo</small></div></div></section>
  </>;
}
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof BarChart3 }) { return <div className="stat-card stat-forest"><span className="stat-icon"><Icon size={17}/></span><span className="stat-label">{label}</span><strong>{value}</strong><span className="stat-meta">sin persistencia</span></div>; }
import * as React from 'react';
