import { ArrowLeft, CalendarDays, Check, Clock3, Filter, ListFilter, Search, SlidersHorizontal, Tag } from 'lucide-react';
import { requisitions, formatMoney, statusTone } from '../../lib/demo-data';
import { ScreenState } from '../ui/demo-notice';
import { RequestRows, SectionTitle, Tone } from './screen-primitives';
import { useState } from 'react';

export function ReviewScreen({ go }: { go: (href: string) => void }) { const [view, setView] = useState<'list'|'kanban'>('list'); const [state, setState] = useState<'ready'|'loading'|'error'|'empty'>('ready'); const rows = requisitions.filter(row => row.status === 'En revisión'); return <><SectionTitle eyebrow="Revisor · Daniel Hernández" title="Bandeja de revisión" description="Normaliza, cotiza y enruta cada solicitud." action={<div className="title-actions"><button className="view-switch is-active" type="button" onClick={() => setView('list')}><ListFilter size={15} /> Lista</button><button className="view-switch" type="button" onClick={() => setView('kanban')}><SlidersHorizontal size={15} /> Kanban</button></div>} /><div className="filter-bar"><div className="search-field"><Search size={16} /><input aria-label="Buscar requisiciones" placeholder="Buscar por número, solicitante o ítem..." disabled aria-disabled="true" title="Disponible al conectar el servicio" /></div><button className="filter-button" type="button" disabled aria-disabled="true" title="Disponible al conectar el servicio"><Filter size={15} /> Obra</button><button className="filter-button" type="button" disabled aria-disabled="true" title="Disponible al conectar el servicio"><Tag size={15} /> Etiqueta</button><button className="filter-button" type="button" disabled aria-disabled="true" title="Disponible al conectar el servicio"><CalendarDays size={15} /> Fecha</button><button className="button button-quiet" type="button" onClick={() => setState(state === 'ready' ? 'loading' : 'ready')}>{state === 'ready' ? 'Probar carga' : 'Volver a datos'}</button><button className="button button-quiet" type="button" onClick={() => setState(state === 'error' ? 'empty' : 'error')}>Probar error/vacío</button></div>{view === 'kanban' ? <Kanban go={go} /> : state === 'ready' ? <section className="panel"><div className="panel-head"><div><h2>Por gestionar</h2><p className="panel-sub">Ordenadas por antigüedad · datos demo</p></div><Tone tone="warning" dot>{rows.length} en revisión</Tone></div><RequestRows rows={rows} onOpen={id => go(`/requisiciones/${id}`)} /></section> : <section className="panel"><ScreenState state={state === 'loading' ? 'loading' : state === 'error' ? 'error' : 'empty'} onRetry={() => setState('ready')} onClear={() => setState('ready')} /></section>}</>; }
function Kanban({ go }: { go: (href: string) => void }) { return <div className="kanban">{['Recibida','En revisión','En aprobación','Aprobada'].map((label, i) => <section className="kanban-column" key={label}><div className="kanban-head"><b>{label}</b><span>{i + 1}</span></div>{requisitions.slice(i, i + 1).map(row => <button className="kanban-card" type="button" key={row.id} onClick={() => go(`/requisiciones/${row.id}`)}><b>{row.id}</b><strong>{row.item}</strong><small>{row.work}</small><span className="money">{formatMoney(row.amount)}</span></button>)}<button className="add-kanban" type="button">+ Agregar</button></section>)}</div>; }

export function ApprovalsScreen({ go }: { go: (href: string) => void }) { const rows = requisitions.filter(row => row.status === 'En aprobación'); return <><SectionTitle eyebrow="Aprobador · Nelson Rincón" title="Mis aprobaciones" description="Solo ves las requisiciones enrutadas a tu bandeja." action={<Tone tone="blue" dot>{rows.length} pendientes</Tone>} /><section className="panel approval-list"><div className="panel-head"><div><h2>Esperando tu decisión</h2><p className="panel-sub">Aprobar o devolver deja una huella de auditoría.</p></div></div>{rows.map(row => <button className="approval-item" type="button" key={row.id} onClick={() => go(`/aprobaciones/${row.id}`)}><div className="approval-item-top"><b>{row.id}</b><Tone tone={statusTone[row.status] || 'blue'}>{row.tag}</Tone></div><h3>{row.item}</h3><div className="approval-meta"><span>{row.work}</span><span className="money">{formatMoney(row.amount)}</span></div></button>)}</section></>; }

export function RequestDetailScreen({ id, go }: { id: string; go: (href: string) => void }) { const row = requisitions.find(item => item.id === id) || requisitions[0]; return <><SectionTitle eyebrow="Detalle de requisición" title={row.id} description={`${row.requestor} · ${row.date}`} action={<button className="button button-secondary" type="button" onClick={() => go('/revision')}><ArrowLeft size={15} /> Volver a bandeja</button>} /><div className="detail-layout"><section className="panel detail-main"><div className="detail-header"><div><Tone tone={statusTone[row.status] || 'muted'} dot>{row.status}</Tone><h2>{row.item}</h2><p>{row.work}</p></div><span className="money detail-amount">{formatMoney(row.amount)}</span></div><div className="detail-fields"><div><span>Solicitante</span><b>{row.requestor}</b></div><div><span>Canal de captura</span><b>{row.channel}</b></div><div><span>Etiqueta</span><b>{row.tag}</b></div><div><span>Fecha requerida</span><b>29 ago 2026</b></div></div><div className="detail-section"><div className="panel-head"><div><div className="eyebrow">Historial de trazabilidad</div><h2>Cada paso, visible</h2></div></div><div className="timeline"><div className="timeline-row"><span className="timeline-dot done"><Check size={11}/></span><span><b>Requisición creada</b><small>{row.requestor} · {row.date}</small></span></div><div className="timeline-row"><span className="timeline-dot current"><Clock3 size={11}/></span><span><b>En revisión</b><small>Daniel tiene la solicitud · demo</small></span></div><div className="timeline-row muted"><span className="timeline-dot"><span/></span><span><b>Pendiente de aprobación</b><small>Se activará al conectar el servicio</small></span></div></div></div></section><aside className="detail-side"><div className="aside-card"><div className="eyebrow">Estado de demo</div><p className="aside-quote">Esta vista valida trazabilidad visual; no guarda cambios.</p></div></aside></div></>; }
