import { type Sql } from "postgres";
import type { Supplier, SupplierDocument, SupplierOrderHistory } from "../domain";
import type { SupplierRepository, SupplierServiceDependencies, SupplierTransaction, SupplierTransactionManager } from "../services/supplier-service";
import { SUPPLIER_DOCUMENT_BUCKET } from "../services/supplier-service";
import { createSupabaseServiceClient } from "./supabase";
import { runtimeEnv } from "../security/env";
import { sharedPostgres } from "./postgres-repositories";
import { asJsonb } from "./jsonb";

type Row = Record<string, unknown>;
const number = (value: unknown) => Number(value ?? 0);
const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
function supplier(row: Row): Supplier { const contact = object(row.contacto), bank = object(row.datos_bancarios); return { id: String(row.id), name: String(row.razon_social), nit: row.nit ? String(row.nit) : null, contact: { ...(typeof contact.name === "string" ? { name: contact.name } : {}), ...(typeof contact.phone === "string" ? { phone: contact.phone } : {}), ...(typeof contact.email === "string" ? { email: contact.email } : {}), ...(typeof contact.address === "string" ? { address: contact.address } : {}) }, bankDetails: { ...(typeof bank.bankName === "string" ? { bankName: bank.bankName } : {}), ...(bank.accountType === "ahorros" || bank.accountType === "corriente" ? { accountType: bank.accountType } : {}), ...(typeof bank.accountNumber === "string" ? { accountNumber: bank.accountNumber } : {}), ...(typeof bank.accountHolder === "string" ? { accountHolder: bank.accountHolder } : {}), ...(typeof bank.accountHolderNit === "string" ? { accountHolderNit: bank.accountHolderNit } : {}) }, active: row.activo === true }; }
function document(row: Row): SupplierDocument { return { id: String(row.id), supplierId: String(row.entidad_id), type: row.tipo as SupplierDocument["type"], name: String(row.nombre_original), mimeType: String(row.mime_type), sizeBytes: number(row.tamano_bytes), ...(row.subido_por ? { uploadedBy: String(row.subido_por) } : {}), uploadedAt: new Date(String(row.fecha)).toISOString(), storagePath: String(row.url_storage) }; }

class PostgresSupplierRepository implements SupplierRepository {
  constructor(private readonly sql: Sql) {}
  async list(): Promise<Supplier[]> { return (await this.sql<Row[]>`select id, razon_social, nit, contacto, datos_bancarios, activo from proveedores order by razon_social`).map(supplier); }
  async get(id: string): Promise<Supplier | null> { const rows = await this.sql<Row[]>`select id, razon_social, nit, contacto, datos_bancarios, activo from proveedores where id=${id}`; return rows[0] ? supplier(rows[0]) : null; }
  async create(value: { name: string; nit?: string | null; contact: Supplier["contact"]; bankDetails: Supplier["bankDetails"]; active: boolean }): Promise<Supplier> { const rows = await this.sql<Row[]>`insert into proveedores (razon_social, nit, contacto, datos_bancarios, activo) values (${value.name}, ${value.nit ?? null}, ${asJsonb(this.sql, value.contact)}, ${asJsonb(this.sql, value.bankDetails)}, ${value.active}) returning id, razon_social, nit, contacto, datos_bancarios, activo`; return supplier(rows[0]); }
  async update(id: string, value: Partial<{ name: string; nit: string | null; contact: Supplier["contact"]; bankDetails: Supplier["bankDetails"]; active: boolean }>): Promise<Supplier | null> { const has = (key: string) => Object.hasOwn(value, key), rows = await this.sql<Row[]>`update proveedores set razon_social=case when ${has("name")} then ${value.name ?? null} else razon_social end, nit=case when ${has("nit")} then ${value.nit ?? null} else nit end, contacto=case when ${has("contact")} then ${asJsonb(this.sql, value.contact ?? {})} else contacto end, datos_bancarios=case when ${has("bankDetails")} then ${asJsonb(this.sql, value.bankDetails ?? {})} else datos_bancarios end, activo=case when ${has("active")} then ${value.active ?? false} else activo end where id=${id} returning id, razon_social, nit, contacto, datos_bancarios, activo`; return rows[0] ? supplier(rows[0]) : null; }
  /** The SECURITY INVOKER view has one row per order and aggregates each requisition item exactly once. */
  async listOrders(supplierId: string): Promise<SupplierOrderHistory[]> { const rows = await this.sql<Row[]>`select orden_id, consecutivo, tipo, estado_cumplimiento, fecha_generacion, valor_total from proveedor_historial_ordenes where proveedor_id=${supplierId} order by fecha_generacion desc`; return rows.map((row) => ({ id: String(row.orden_id), consecutive: String(row.consecutivo), type: row.tipo as SupplierOrderHistory["type"], status: row.estado_cumplimiento as SupplierOrderHistory["status"], generatedAt: new Date(String(row.fecha_generacion)).toISOString(), total: number(row.valor_total) })); }
  async listDocuments(supplierId: string): Promise<SupplierDocument[]> { return (await this.sql<Row[]>`select id, entidad_id, tipo, nombre_original, mime_type, tamano_bytes, subido_por, fecha, url_storage from adjuntos where entidad='proveedor' and entidad_id=${supplierId} and storage_bucket=${SUPPLIER_DOCUMENT_BUCKET} order by fecha desc`).map(document); }
  async getDocument(supplierId: string, documentId: string): Promise<SupplierDocument | null> { const rows = await this.sql<Row[]>`select id, entidad_id, tipo, nombre_original, mime_type, tamano_bytes, subido_por, fecha, url_storage from adjuntos where entidad='proveedor' and entidad_id=${supplierId} and id=${documentId} and storage_bucket=${SUPPLIER_DOCUMENT_BUCKET}`; return rows[0] ? document(rows[0]) : null; }
  async insertDocument(value: SupplierDocument): Promise<SupplierDocument> { const rows = await this.sql<Row[]>`insert into adjuntos (id, entidad, entidad_id, storage_bucket, url_storage, tipo, nombre_original, mime_type, tamano_bytes, subido_por, fecha) values (${value.id}, 'proveedor', ${value.supplierId}, ${SUPPLIER_DOCUMENT_BUCKET}, ${value.storagePath}, ${value.type}, ${value.name}, ${value.mimeType}, ${value.sizeBytes}, ${value.uploadedBy ?? null}, ${value.uploadedAt}) returning id, entidad_id, tipo, nombre_original, mime_type, tamano_bytes, subido_por, fecha, url_storage`; return document(rows[0]); }
}
class PostgresSupplierTransactions implements SupplierTransactionManager {
  constructor(private readonly sql: Sql) {}
  async transaction<T>(supplierId: string | undefined, work: (tx: SupplierTransaction) => Promise<T>): Promise<T> { return this.sql.begin(async (sql) => { if (supplierId) await sql`select id from proveedores where id=${supplierId} for update`; const repository = new PostgresSupplierRepository(sql as unknown as Sql); const tx: SupplierTransaction = { suppliers: repository, features: { isEnabled: async (name) => (await sql<{ activo: boolean }[]>`select activo from modulos where nombre=${name} for share`)[0]?.activo === true }, audit: { append: async (event) => { await sql`insert into auditoria (entidad, entidad_id, evento, origen, usuario_id, fecha, datos_json) values (${event.entity}, ${event.entityId}, ${event.event.toUpperCase().replace(/[^A-Z0-9_]/g, "_")}, ${event.origin}, ${event.actorId ?? null}, ${event.at.toISOString()}, ${asJsonb(sql, event.data ?? {})})`; } } }; return work(tx); }) as Promise<T>; }
}
class SupabaseSupplierStorage {
  private readonly client = createSupabaseServiceClient();
  async createUploadUrl(path: string): Promise<{ url: string }> { const bucket = this.client.storage.from(SUPPLIER_DOCUMENT_BUCKET), result = await bucket.createSignedUploadUrl(path, { upsert: false }); if (result.error || !result.data?.signedUrl) throw new Error("SUPPLIER_STORAGE_UPLOAD_URL_FAILED"); return { url: result.data.signedUrl }; }
  async info(path: string): Promise<{ sizeBytes: number; mimeType: string } | null> { const bucket = this.client.storage.from(SUPPLIER_DOCUMENT_BUCKET) as unknown as { info(path: string): Promise<{ data: { metadata?: { size?: number | string; mimetype?: string; contentType?: string }; size?: number | string; mimetype?: string; content_type?: string } | null; error: unknown }> }; const result = await bucket.info(path); if (result.error || !result.data) return null; const metadata = result.data.metadata ?? {}, size = Number(metadata.size ?? result.data.size), mimeType = String(metadata.mimetype ?? metadata.contentType ?? result.data.mimetype ?? result.data.content_type ?? ""); return Number.isInteger(size) && size >= 0 && mimeType ? { sizeBytes: size, mimeType } : null; }
  async createDownloadUrl(path: string, expiresInSeconds: number): Promise<string> { const result = await this.client.storage.from(SUPPLIER_DOCUMENT_BUCKET).createSignedUrl(path, expiresInSeconds); if (result.error || !result.data?.signedUrl) throw new Error("SUPPLIER_STORAGE_DOWNLOAD_URL_FAILED"); return result.data.signedUrl; }
}
export function createSupplierServiceDependencies(databaseUrl = runtimeEnv().DATABASE_URL): SupplierServiceDependencies { const sql = sharedPostgres(databaseUrl); return { transactions: new PostgresSupplierTransactions(sql), storage: new SupabaseSupplierStorage(), clock: { now: () => new Date() }, ids: { next: () => crypto.randomUUID() } }; }
