import { describe, expect, it } from "vitest";
import { processKapsoEvent } from "../../lib/infrastructure/kapso-processor";
import type { KapsoProcessingStore } from "../../lib/infrastructure/kapso";

const event = { eventId: "evt-1", type: "flow_submission" as const, receivedAt: "2026-08-24T00:00:00.000Z", submission: { eventId: "evt-1", phone: "+573001234567", workId: "work", requiredDate: "2026-08-30", type: "compra" as const, requesterName: "Maestro", items: [] } };
function store(options: { failCompleteOnce?: boolean } = {}): KapsoProcessingStore { let state: "new" | "processing" | "completed" = "new", completionAttempts = 0, requisitionId: string | null = null; return { claim: async () => { if (state === "completed") return "completed"; if (state === "processing") return "in_progress"; state = "processing"; return "claimed"; }, complete: async (_eventId, id) => { completionAttempts++; if (options.failCompleteOnce && completionAttempts === 1) throw new Error("completion interrupted"); requisitionId = id ?? null; state = "completed"; }, release: async () => { state = "new"; }, findRequisitionId: async () => requisitionId }; }
describe("Kapso idempotency coordinator", () => {
  it("allows exactly one concurrent creator", async () => { const durable = store(); let creates = 0; const creator = { findExisting: async () => null, create: async () => { creates++; await new Promise((resolve) => setTimeout(resolve, 5)); return { id: "req", consecutive: "REQ", type: "compra" as const, workId: "work", channel: "whatsapp" as const, requiredDate: "2026-08-30", status: "enviada" as const, items: [] }; } }; const [first, second] = await Promise.all([processKapsoEvent(durable, creator, event), processKapsoEvent(durable, creator, event)]); expect([first, second].sort()).toEqual(["created", "in_progress"]); expect(creates).toBe(1); });
  it("releases a failed claim so the retry creates once successfully", async () => { const durable = store(); let attempts = 0; const creator = { findExisting: async () => null, create: async () => { attempts++; if (attempts === 1) throw new Error("db down"); return { id: "req", consecutive: "REQ", type: "compra" as const, workId: "work", channel: "whatsapp" as const, requiredDate: "2026-08-30", status: "enviada" as const, items: [] }; } }; await expect(processKapsoEvent(durable, creator, event)).rejects.toThrow("db down"); await expect(processKapsoEvent(durable, creator, event)).resolves.toBe("created"); expect(attempts).toBe(2); });
  it("recovers a crash after creation without creating a duplicate requisition", async () => { const durable = store({ failCompleteOnce: true }); let created = false, creates = 0; const requisition = { id: "req", consecutive: "REQ", type: "compra" as const, workId: "work", channel: "whatsapp" as const, requiredDate: "2026-08-30", status: "enviada" as const, items: [] }; const creator = { findExisting: async () => created ? requisition : null, create: async () => { creates++; created = true; return requisition; } }; await expect(processKapsoEvent(durable, creator, event)).resolves.toBe("duplicate"); await expect(processKapsoEvent(durable, creator, event)).resolves.toBe("duplicate"); expect(creates).toBe(1); });
  it("allows a lease-expired processing claim to be recovered while a live one stays in progress", async () => { let claimCalls = 0, creates = 0; const durable: KapsoProcessingStore = { claim: async () => ++claimCalls === 1 ? "in_progress" : "claimed", complete: async () => {}, release: async () => {}, findRequisitionId: async () => null }; const creator = { findExisting: async () => null, create: async () => { creates++; return { id: "recovered", consecutive: "REQ", type: "compra" as const, workId: "work", channel: "whatsapp" as const, requiredDate: "2026-08-30", status: "enviada" as const, items: [] }; } }; await expect(processKapsoEvent(durable, creator, event)).resolves.toBe("in_progress"); await expect(processKapsoEvent(durable, creator, event)).resolves.toBe("created"); expect(creates).toBe(1); });
});
