// Contrato local del esquema. Regenerar con `supabase gen types typescript --local`
// cuando el proyecto Supabase exista; no sustituye las migraciones como fuente de verdad.
export type UserRole = "solicitante" | "revisor" | "aprobador" | "contabilidad" | "admin_mizar" | "admin_sixteam";
export type RequestStatus = "enviada" | "en_revision" | "en_aprobacion" | "aprobada" | "devuelta" | "declinada";
export type RequestChannel = "web" | "publico" | "whatsapp";
export type DocumentType = "REQ" | "OC" | "OP";
export type KapsoProcessingStatus = "processing" | "retryable" | "completed";
export type KapsoEventType = "flow_submission" | "message_status";

export type Database = {
  public: {
    Tables: {
      sociedades: { Row: { id: string; nombre: string; nit: string | null; activa: boolean; created_at: string; updated_at: string }; Insert: Partial<{ id: string; nombre: string; nit: string | null; activa: boolean }>; Update: Partial<{ nombre: string; nit: string | null; activa: boolean }> };
      usuarios: { Row: { id: string; nombre: string; email: string; telefono: string | null; estado: "activo" | "inactivo"; created_at: string; updated_at: string }; Insert: { id: string; nombre: string; email: string; telefono?: string | null }; Update: Partial<{ nombre: string; email: string; telefono: string | null; estado: "activo" | "inactivo" }> };
      usuario_roles: { Row: { usuario_id: string; rol: UserRole; created_at: string }; Insert: { usuario_id: string; rol: UserRole }; Update: never };
      modulos: { Row: { nombre: string; activo: boolean; roles_acceso: UserRole[]; descripcion: string | null; updated_at: string }; Insert: { nombre: string; activo?: boolean; roles_acceso?: UserRole[]; descripcion?: string | null }; Update: Partial<{ activo: boolean; roles_acceso: UserRole[]; descripcion: string | null }> };
      obras: { Row: { id: string; nombre: string; sociedad_id: string; estado: "activa" | "cerrada"; public_submission_enabled: boolean; require_authorized_requester: boolean; created_at: string; updated_at: string }; Insert: { nombre: string; sociedad_id: string; estado?: "activa" | "cerrada" }; Update: Partial<{ nombre: string; sociedad_id: string; estado: "activa" | "cerrada"; public_submission_enabled: boolean; require_authorized_requester: boolean }> };
      obra_solicitantes_autorizados: { Row: { id: string; obra_id: string; nombre: string; telefono: string; activo: boolean; created_at: string; updated_at: string }; Insert: { obra_id: string; nombre: string; telefono: string; activo?: boolean }; Update: Partial<{ nombre: string; telefono: string; activo: boolean }> };
      etiquetas: { Row: { id: string; nombre: string; aprobador_id: string | null; activa: boolean; created_at: string; updated_at: string }; Insert: { nombre: string; aprobador_id?: string | null; activa?: boolean }; Update: Partial<{ nombre: string; aprobador_id: string | null; activa: boolean }> };
      proveedores: { Row: { id: string; razon_social: string; nit: string | null; contacto: Json; datos_bancarios: Json; activo: boolean; created_at: string; updated_at: string }; Insert: { razon_social: string; nit?: string | null; contacto?: Json; datos_bancarios?: Json; activo?: boolean }; Update: Partial<{ razon_social: string; nit: string | null; contacto: Json; datos_bancarios: Json; activo: boolean }> };
      items: { Row: { id: string; nombre: string; nombre_normalizado: string; especificacion: string | null; unidad_defecto: string; categoria: string | null; estado: "activo" | "pendiente_normalizacion" | "inactivo" | "fusionado"; created_at: string; updated_at: string }; Insert: { nombre: string; nombre_normalizado: string; unidad_defecto: string; especificacion?: string | null; categoria?: string | null }; Update: Partial<{ nombre: string; nombre_normalizado: string; unidad_defecto: string; especificacion: string | null; categoria: string | null; estado: "activo" | "pendiente_normalizacion" | "inactivo" | "fusionado" }> };
      requisiciones: { Row: { id: string; consecutivo: string; tipo: "compra" | "pago"; obra_id: string; solicitante_id: string | null; canal: RequestChannel; estado: RequestStatus; etiqueta_id: string | null; fecha_requerida: string | null; kapso_event_id: string | null; created_at: string; updated_at: string }; Insert: { tipo: "compra" | "pago"; obra_id: string; solicitante_id?: string | null; canal: RequestChannel; consecutivo?: string; kapso_event_id?: string | null }; Update: Partial<{ estado: RequestStatus; etiqueta_id: string | null; motivo_declinacion: string | null; motivo_devolucion: string | null; kapso_event_id: string | null }> };
      requisicion_items: { Row: { id: string; requisicion_id: string; item_id: string | null; descripcion_libre: string | null; cantidad: number; unidad: string; proveedor_final_id: string | null; valor_base: number; iva: number; valor_total: number; created_at: string; updated_at: string }; Insert: { requisicion_id: string; item_id?: string | null; descripcion_libre?: string | null; cantidad: number; unidad: string }; Update: Partial<{ item_id: string | null; descripcion_libre: string | null; cantidad: number; unidad: string; proveedor_final_id: string | null; valor_base: number; iva: number }> };
      ordenes: { Row: { id: string; consecutivo: string; tipo: "OC" | "OP"; requisicion_id: string; proveedor_id: string | null; estado_cumplimiento: "generada" | "cumplida" | "no_cumplida" | "no_necesario"; created_at: string; updated_at: string }; Insert: { tipo: "OC" | "OP"; requisicion_id: string; proveedor_id?: string | null; consecutivo?: string }; Update: Partial<{ estado_cumplimiento: "generada" | "cumplida" | "no_cumplida" | "no_necesario"; pdf_url: string | null }> };
      gastos: { Row: { id: string; obra_id: string; origen: "requisicion" | "caja_menor"; referencia_id: string; etiqueta_id: string | null; proveedor_id: string | null; fecha: string; valor_base: number; iva: number; valor_total: number; periodo: string; created_at: string; updated_at: string }; Insert: never; Update: never };
      gastos_reparto: { Row: { gasto_id: string; obra_id: string; valor: number; created_at: string; updated_at: string }; Insert: never; Update: never };
      caja_menor: { Row: { id: string; obra_id: string; fecha: string; concepto: string; etiqueta_id: string | null; proveedor_id: string | null; valor: number; registrado_por: string; gasto_id: string | null; created_at: string; updated_at: string }; Insert: { obra_id: string; fecha: string; concepto: string; valor: number; registrado_por: string; etiqueta_id?: string | null; proveedor_id?: string | null }; Update: Partial<{ fecha: string; concepto: string; etiqueta_id: string | null; proveedor_id: string | null; valor: number }> };
      adjuntos: { Row: { id: string; entidad: string; entidad_id: string; url_storage: string; tipo: string; nombre_original: string; tamano_bytes: number | null; storage_bucket: string | null; mime_type: string | null; checksum_sha256: string | null; subido_por: string | null; fecha: string }; Insert: { entidad: string; entidad_id: string; url_storage: string; tipo: string; nombre_original: string; tamano_bytes?: number | null; storage_bucket?: string | null; mime_type?: string | null; checksum_sha256?: string | null; subido_por?: string | null }; Update: never };
      auditoria: { Row: { id: number; entidad: string; entidad_id: string | null; evento: string; origen: "web" | "mcp" | "kapso" | "importacion" | "sistema"; usuario_id: string | null; fecha: string; datos_json: Json }; Insert: never; Update: never };
      kapso_procesamiento: { Row: { event_id: string; tipo_evento: KapsoEventType; estado: KapsoProcessingStatus; requisicion_id: string | null; payload: Json; created_at: string; updated_at: string }; Insert: { event_id: string; tipo_evento: KapsoEventType; estado: KapsoProcessingStatus; requisicion_id?: string | null; payload: Json }; Update: Partial<{ estado: KapsoProcessingStatus; requisicion_id: string | null; payload: Json }> };
    };
    Views: { gasto_distribucion: { Row: { gasto_id: string; obra_id: string; fecha: string; periodo: string; etiqueta_id: string | null; proveedor_id: string | null; origen: "requisicion" | "caja_menor"; valor: number } }; proveedor_historial_ordenes: { Row: { proveedor_id: string; orden_id: string; consecutivo: string; tipo: "OC" | "OP"; estado_cumplimiento: "generada" | "cumplida" | "no_cumplida" | "no_necesario"; fecha_generacion: string; requisicion_id: string; obra_id: string; cantidad_items: number; valor_base: number; iva: number; valor_total: number } } };
    Functions: {
      crear_requisicion_publica: { Args: { p_obra_id: string; p_codigo: string; p_nombre: string; p_telefono: string; p_tipo: "compra" | "pago"; p_fecha_requerida?: string | null; p_destino?: string | null; p_observaciones?: string | null; p_items: Json }; Returns: string };
      consultar_estado_requisicion_publica: { Args: { p_requisicion_id: string; p_codigo: string }; Returns: { consecutivo: string; estado: RequestStatus; updated_at: string }[] };
    };
    Enums: { rol_usuario: UserRole; estado_requisicion: RequestStatus; canal_requisicion: RequestChannel; tipo_documento: DocumentType };
    CompositeTypes: Record<string, never>;
  };
};

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
