import { PDFDocument, StandardFonts } from "pdf-lib";
import type { OrderDocument, ReportExpense } from "./types";

const cop = new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 });
export async function buildOrderPdf(order: OrderDocument): Promise<Uint8Array> {
  const pdf = await PDFDocument.create(), font = await pdf.embedFont(StandardFonts.Helvetica), bold = await pdf.embedFont(StandardFonts.HelveticaBold); let page = pdf.addPage([595, 842]), y = 790;
  const header = () => { page.drawText(`${order.type === "OC" ? "ORDEN DE COMPRA" : "ORDEN DE PAGO"} - PROVISIONAL P4 PENDIENTE`, { x: 50, y, size: 14, font: bold }); y -= 28; page.drawText(`${order.consecutive} | Obra: ${order.work} | Fecha: ${order.date}`, { x: 50, y, size: 9, font }); y -= 16; };
  const line = (value: string, size = 9) => { if (y < 65) { page = pdf.addPage([595, 842]); y = 790; header(); } for (const fragment of value.match(/.{1,82}(?:\s|$)|\S+?(?:\s|$)/g) ?? [value]) { page.drawText(fragment.trim(), { x: 55, y, size, font }); y -= size + 5; } };
  header(); line(`Proveedor: ${order.supplier ?? "Por definir"}`); for (const item of order.items) line(`${item.quantity} ${item.unit} - ${item.description} - ${cop.format(item.total)}`); y -= 8; line(`TOTAL: ${cop.format(order.total)}`, 12); line("Documento provisional generado por Plataforma Mizar", 8); return pdf.save();
}
export async function buildPartnersExpensePdf(title: string, expenses: readonly ReportExpense[]): Promise<Uint8Array> { const pdf = await PDFDocument.create(), font = await pdf.embedFont(StandardFonts.Helvetica), bold = await pdf.embedFont(StandardFonts.HelveticaBold); let page = pdf.addPage([595, 842]), y = 790, total = 0, pageNumber = 1; const header = () => { page.drawText(`${title} - PROVISIONAL P4 PENDIENTE`, { x: 50, y, size: 16, font: bold }); y -= 20; page.drawText(`Periodo: ${expenses[0]?.date.slice(0, 7) ?? "sin datos"} | Página ${pageNumber}`, { x: 50, y, size: 9, font }); y -= 20; }; header(); for (const expense of expenses) { if (y < 65) { page = pdf.addPage([595, 842]); pageNumber++; y = 790; header(); } total += expense.total; page.drawText(`${expense.date} | ${expense.work.slice(0, 25)} | ${(expense.tag ?? "").slice(0, 20)} | ${cop.format(expense.total)}`, { x: 50, y, size: 9, font }); y -= 15; } if (y < 65) { page = pdf.addPage([595, 842]); y = 790; header(); } page.drawText(`TOTAL: ${cop.format(total)}`, { x: 50, y: y - 12, size: 13, font: bold }); return pdf.save(); }
