'use client';

import Link from 'next/link';
import { useActionState } from 'react';
import { LockKeyhole, Mail, ArrowRight, AlertCircle, CheckCircle2 } from 'lucide-react';
import { requestPasswordReset, signInAction, updatePassword, type AuthActionState } from '../../app/auth-actions';

export function AuthFrame({ children, title, description }: { children: React.ReactNode; title: string; description: string }) { const demoMode = process.env.NEXT_PUBLIC_DEMO_MODE === 'true'; return <main className="auth-page"><div className="auth-brand"><span className="brand-mark">M</span><span><b>MIZAR</b><small>Control de obra</small></span></div><section className="auth-card"><div className="eyebrow">Acceso seguro</div><h1>{title}</h1><p className="auth-description">{description}</p>{demoMode && <p className="auth-feedback auth-success" role="status"><CheckCircle2 size={15} />Modo demo activo: este formulario no crea un bypass de autenticación.</p>}{children}</section><p className="auth-footer">Plataforma de Mizar · Las sesiones requieren un usuario autorizado.</p></main>; }

function Feedback({ state }: { state: AuthActionState }) { return <>{state.error && <p className="auth-feedback auth-error" role="alert"><AlertCircle size={15} />{state.error}</p>}{state.success && <p className="auth-feedback auth-success" role="status"><CheckCircle2 size={15} />{state.success}</p>}</>; }

export function LoginForm({ next = '/', updated = false, callbackError = false, accessDenied = false, configError = false }: { next?: string; updated?: boolean; callbackError?: boolean; accessDenied?: boolean; configError?: boolean }) { const [state, action, pending] = useActionState(signInAction, {}); return <><Feedback state={state} />{updated && <p className="auth-feedback auth-success" role="status"><CheckCircle2 size={15} />Contraseña actualizada. Ya puedes iniciar sesión.</p>}{callbackError && <p className="auth-feedback auth-error" role="alert"><AlertCircle size={15} />El enlace de autenticación no es válido o ya expiró.</p>}{accessDenied && <p className="auth-feedback auth-error" role="alert"><AlertCircle size={15} />Tu usuario no tiene un rol Mizar activo. Solicita acceso al administrador.</p>}{configError && <p className="auth-feedback auth-error" role="alert"><AlertCircle size={15} />El servicio no está disponible en este momento. Intenta de nuevo en unos minutos; si continúa, contacta a soporte.</p>}<form action={action} className="auth-form"><input type="hidden" name="next" value={next} /><label className="field"><span>Correo electrónico</span><div className="auth-input"><Mail size={16} /><input name="email" type="email" autoComplete="email" required /></div></label><label className="field"><span>Contraseña</span><div className="auth-input"><LockKeyhole size={16} /><input name="password" type="password" autoComplete="current-password" required /></div></label><button className="button button-dark auth-submit" type="submit" disabled={pending}>{pending ? 'Comprobando…' : 'Iniciar sesión'}<ArrowRight size={15} /></button></form><Link className="auth-link" href={`/recuperar-clave?next=${encodeURIComponent(next)}`}>¿Olvidaste tu contraseña?</Link></>; }

export function ResetForm() { const [state, action, pending] = useActionState(requestPasswordReset, {}); return <><Feedback state={state} /><form action={action} className="auth-form"><label className="field"><span>Correo electrónico</span><div className="auth-input"><Mail size={16} /><input name="email" type="email" autoComplete="email" required /></div></label><button className="button button-dark auth-submit" type="submit" disabled={pending}>{pending ? 'Solicitando…' : 'Enviar instrucciones'}<ArrowRight size={15} /></button></form><Link className="auth-link" href="/login">Volver a iniciar sesión</Link></>; }

export function PasswordForm() { const [state, action, pending] = useActionState(updatePassword, {}); return <><Feedback state={state} /><form action={action} className="auth-form"><label className="field"><span>Nueva contraseña</span><div className="auth-input"><LockKeyhole size={16} /><input name="password" type="password" autoComplete="new-password" required minLength={8} /></div></label><label className="field"><span>Confirmar contraseña</span><div className="auth-input"><LockKeyhole size={16} /><input name="confirmation" type="password" autoComplete="new-password" required minLength={8} /></div></label><button className="button button-dark auth-submit" type="submit" disabled={pending}>{pending ? 'Guardando…' : 'Cambiar contraseña'}<ArrowRight size={15} /></button></form></>; }
