import { describe, expect, it } from "vitest";
import type { AuditEvent } from "../../lib/domain";
import { CatalogService, canManageCatalog, type CatalogKind, type CatalogRecord, type ServiceDependencies } from "../../lib/services";

const reviewer = { id: "daniel", roles: ["revisor"] as const };
const mizarAdmin = { id: "mizar", roles: ["admin_mizar"] as const };
const sixteam = { id: "sixteam", roles: ["admin_sixteam"] as const };

function deps(options: { feature?: boolean; transactionFeature?: boolean; eligibleApprover?: boolean; failAudit?: boolean; uniqueViolation?: boolean } = {}) {
  const records = new Map<string, CatalogRecord>(), audits: AuditEvent[] = [];
  const catalog = {
    create: async (kind: CatalogKind, value: Omit<CatalogRecord, "id">) => { if (options.uniqueViolation) throw Object.assign(new Error("duplicate"), { code: "23505" }); const id = `id-${records.size + 1}`, created = { ...value, id } as CatalogRecord; records.set(`${kind}:${id}`, structuredClone(created)); return created; },
    get: async (kind: CatalogKind, id: string) => records.get(`${kind}:${id}`) ? structuredClone(records.get(`${kind}:${id}`)!) : null,
    update: async (kind: CatalogKind, id: string, value: Partial<Omit<CatalogRecord, "id">>) => { const prior = records.get(`${kind}:${id}`); if (!prior) throw new Error("CATALOG_NOT_FOUND"); const next = { ...prior, ...value } as CatalogRecord; records.set(`${kind}:${id}`, structuredClone(next)); return next; },
    findSupplierDuplicate: async (value: { name: string; nit?: string }, exceptId?: string) => [...records.entries()].find(([key, record]) => key.startsWith("suppliers:") && record.id !== exceptId && (record.name.toLowerCase() === value.name.toLowerCase() || ("nit" in record && Boolean(value.nit) && record.nit === value.nit)))?.[1].id ?? null,
    isEligibleApprover: async () => options.eligibleApprover ?? true,
  };
  const audit = { append: async (event: AuditEvent) => { if (options.failAudit) throw new Error("audit failed"); audits.push(event); }, list: async () => [] as AuditEvent[] };
  const transaction = async <T>(_lock: string | undefined, work: (repositories: Parameters<ServiceDependencies["transactions"]["transaction"]>[1] extends (repositories: infer R) => Promise<unknown> ? R : never) => Promise<T>) => { const snapshot = structuredClone([...records.entries()]), auditSnapshot = structuredClone(audits); try { return await work({ catalogs: catalog, audit, requisitions: {} as never, orders: {} as never, expenses: {} as never, pettyCash: {} as never, consecutives: {} as never, tags: {} as never, features: { isEnabled: async () => options.transactionFeature ?? options.feature ?? false }, items: {} as never, notifications: {} as never }); } catch (error) { records.clear(); for (const [key, value] of snapshot) records.set(key, value); audits.splice(0, audits.length, ...auditSnapshot); throw error; } };
  const service = new CatalogService({ transactions: { transaction }, audit, features: { isEnabled: async () => options.feature ?? false }, clock: { now: () => new Date("2026-08-24T00:00:00.000Z") } } as unknown as ServiceDependencies);
  return { service, records, audits };
}

describe("CatalogService", () => {
  it("does not expose the management view to operational or requester roles", () => { expect(canManageCatalog({ id: "sol", roles: ["solicitante"] }, "suppliers", true)).toBe(false); expect(canManageCatalog({ id: "approver", roles: ["aprobador"] }, "works", true)).toBe(false); expect(canManageCatalog(mizarAdmin, "items", true)).toBe(false); expect(canManageCatalog(mizarAdmin, "suppliers", false)).toBe(false); });
  it("honors the strongest role and rechecks Mizar feature in the write transaction", async () => { const service = deps({ feature: true, transactionFeature: false }).service; await expect(service.create("works", { name: "Bloqueada", societyId: "soc", active: true }, mizarAdmin)).rejects.toMatchObject({ code: "FEATURE_DISABLED" }); const dualSix = { id: "dual-six", roles: ["admin_mizar", "admin_sixteam"] as const }, dualReviewer = { id: "dual-reviewer", roles: ["admin_mizar", "revisor"] as const }; const disabled = deps(); await expect(disabled.service.create("works", { name: "Permitida Sixteam", societyId: "soc", active: true }, dualSix)).resolves.toMatchObject({ name: "Permitida Sixteam" }); await expect(disabled.service.create("items", { name: "Permitido Daniel", unit: "und", active: true }, dualReviewer)).resolves.toMatchObject({ name: "Permitido Daniel" }); await expect(disabled.service.create("suppliers", { name: "Permitido proveedor", active: true }, dualReviewer)).resolves.toMatchObject({ name: "Permitido proveedor" }); });
  it("keeps item master ownership with reviewer/Sixteam even after Mizar self-service", async () => { const enabled = deps({ feature: true }); await expect(enabled.service.create("items", { name: "Cemento", unit: "bulto", active: true }, mizarAdmin)).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(enabled.service.create("items", { name: "Cemento", unit: "bulto", active: true }, reviewer)).resolves.toMatchObject({ name: "Cemento", active: true }); await expect(enabled.service.create("items", { name: "Arena", unit: "m3", active: true }, sixteam)).resolves.toMatchObject({ name: "Arena" }); });
  it("permits only gated Mizar self-service and prevents reasonable supplier duplicates", async () => { const disabled = deps(); await expect(disabled.service.create("works", { name: "Obra Norte", societyId: "soc-1", active: true }, mizarAdmin)).rejects.toMatchObject({ code: "FEATURE_DISABLED" }); const enabled = deps({ feature: true }); await expect(enabled.service.create("works", { name: "Obra Norte", societyId: "soc-1", active: true }, mizarAdmin)).resolves.toMatchObject({ name: "Obra Norte" }); await enabled.service.create("suppliers", { name: "Arenera Mizar", nit: "900-123", active: true }, mizarAdmin); await expect(enabled.service.create("suppliers", { name: "Arenera Mizar", phone: "+573001234567", active: true }, mizarAdmin)).rejects.toMatchObject({ code: "CONFLICT" }); await expect(enabled.service.create("works", { name: "No permitido", societyId: "soc-2", active: true }, reviewer)).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("translates database unique constraints into catalog conflicts", async () => { const race = deps({ uniqueViolation: true }); await expect(race.service.create("suppliers", { name: "Arenera concurrente", nit: "900999", active: true }, reviewer)).rejects.toMatchObject({ code: "CONFLICT", message: expect.stringMatching(/proveedor/i) }); await expect(race.service.create("works", { name: "Obra duplicada", societyId: "soc", active: true }, sixteam)).rejects.toMatchObject({ code: "CONFLICT", message: expect.stringMatching(/catálogo/i) }); });
  it("requires an active eligible approver for active tags", async () => { const invalid = deps({ eligibleApprover: false }).service; await expect(invalid.create("tags", { name: "Sin aprobador", active: true }, sixteam)).rejects.toMatchObject({ code: "INVALID_INPUT" }); await expect(invalid.create("tags", { name: "Aprobador inactivo", approverId: "approver", active: true }, sixteam)).rejects.toMatchObject({ code: "INVALID_INPUT" }); const fixture = deps(), tag = await fixture.service.create("tags", { name: "Temporal", active: false }, sixteam); await expect(fixture.service.patch("tags", tag.id, { active: true }, sixteam)).rejects.toMatchObject({ code: "INVALID_INPUT" }); });
  it("deactivates reversibly and audits redacted before/after inside the UoW", async () => { const fixture = deps(), supplier = await fixture.service.create("suppliers", { name: "Proveedor Seguro", nit: "900123", phone: "+573001234567", email: "contacto@example.test", active: true }, reviewer); const patched = await fixture.service.patch("suppliers", supplier.id, { active: false }, reviewer); expect(patched).toMatchObject({ active: false }); expect(fixture.audits.at(-1)).toMatchObject({ event: "actualizada", data: { before: { nitConfigured: true, contactConfigured: true, active: true }, after: { active: false } } }); expect(JSON.stringify(fixture.audits)).not.toContain("300123"); expect(JSON.stringify(fixture.audits)).not.toContain("example.test"); const failing = deps({ failAudit: true }); await expect(failing.service.create("suppliers", { name: "Debe revertirse", active: true }, reviewer)).rejects.toThrow("audit failed"); expect(failing.records.size).toBe(0); });
  it("clears optional data durably and permits clearing an approver only while inactive", async () => { const fixture = deps(), supplier = await fixture.service.create("suppliers", { name: "Proveedor editable", nit: "900123", phone: "+573001234567", email: "contacto@example.test", address: "Calle 1", active: true }, reviewer); await fixture.service.patch("suppliers", supplier.id, { nit: null, phone: null, email: null, address: null }, reviewer); const reloadedSupplier = fixture.records.get(`suppliers:${supplier.id}`) as Extract<CatalogRecord, { nit?: string | null }>; expect(reloadedSupplier).toMatchObject({ nit: null, phone: null, email: null, address: null }); const item = await fixture.service.create("items", { name: "Ítem editable", unit: "und", specification: "detalle", category: "obra", active: true }, reviewer); await fixture.service.patch("items", item.id, { specification: null, category: null }, reviewer); expect(fixture.records.get(`items:${item.id}`)).toMatchObject({ specification: null, category: null }); const tag = await fixture.service.create("tags", { name: "Tag editable", approverId: "eligible", active: true }, sixteam); await expect(fixture.service.patch("tags", tag.id, { approverId: null }, sixteam)).rejects.toMatchObject({ code: "INVALID_INPUT" }); await expect(fixture.service.patch("tags", tag.id, { approverId: null, active: false }, sixteam)).resolves.toMatchObject({ approverId: null, active: false }); });
});
