import { describe, expect, it } from "vitest";
import { DomainError, type AuditEvent, type Expense, type ExpenseShare, type Order, type PettyCash, type Requisition } from "../../lib/domain";
import { ProcurementService, type ServiceDependencies } from "../../lib/services";

function fakeDeps(): ServiceDependencies & { req: Map<string, Requisition>; ordersData: Order[]; expensesData: Expense[]; pettyData: PettyCash[]; proposedItems: Map<string, string>; notificationData: Array<{ userId?: string; phone?: string; channel: "whatsapp" | "interno"; template: string; payload: Record<string, unknown> }>; audits: AuditEvent[]; shares: ExpenseShare[]; visibleActors: string[]; transactionCalls: number } {
  const req = new Map<string, Requisition>(), ordersData: Order[] = [], expensesData: Expense[] = [], petty: PettyCash[] = [], audits: AuditEvent[] = [], shares: ExpenseShare[] = [], visibleActors: string[] = []; let seq = 0;
  const requisitions = { get: async (id: string) => req.get(id) ? structuredClone(req.get(id)!) : null, save: async (r: Requisition) => void req.set(r.id, structuredClone(r)), list: async () => [...req.values()].map((value) => structuredClone(value)), listVisibleTo: async (actor: { id: string }) => { visibleActors.push(`req:${actor.id}`); return [...req.values()].filter((r) => actor.id === "daniel" || r.approverId === actor.id).map((value) => structuredClone(value)); } };
  const orders = { save: async (o: Order) => { const i = ordersData.findIndex((x) => x.id === o.id); if (i >= 0) ordersData[i] = o; else ordersData.push(o); }, list: async () => ordersData, listVisibleTo: async (actor: { id: string }) => { visibleActors.push(`order:${actor.id}`); return actor.id === "daniel" ? ordersData : ordersData.filter((o) => o.requisitionId.includes(actor.id)); }, listByRequisition: async (id: string) => ordersData.filter((o) => o.requisitionId === id), get: async (id: string) => ordersData.find((o) => o.id === id) ?? null };
  const expenses = { get: async (id: string) => expensesData.find((entry) => entry.id === id) ?? null, save: async (e: Expense) => void expensesData.push(e), saveShares: async (s: ExpenseShare[]) => { const id = s[0]?.expenseId; if (id) for (let index = shares.length - 1; index >= 0; index--) if (shares[index].expenseId === id) shares.splice(index, 1); shares.push(...s); }, list: async () => expensesData, listVisibleTo: async (actor: { id: string }) => { visibleActors.push(`expense:${actor.id}`); return actor.id === "daniel" ? expensesData : []; }, listByReference: async (id: string) => expensesData.filter((e) => e.referenceId === id || ordersData.some((o) => o.id === e.referenceId && o.requisitionId === id)) };
  const proposed = new Map<string, string>(), notificationData: Array<{ userId?: string; phone?: string; channel: "whatsapp" | "interno"; template: string; payload: Record<string, unknown> }> = [], audit = { append: async (a: AuditEvent) => void audits.push(a), list: async (entity: string, entityId: string) => audits.filter((entry) => entry.entity === entity && entry.entityId === entityId) }, consecutives = { take: async (p: "REQ" | "OC" | "OP", y: number) => `${p}-${y}-${String(++seq).padStart(4, "0")}` }, tags = { getApproverId: async (tag: string) => tag === "tag" ? "nelson" : null }, features = { isEnabled: async (name: string) => name === "ordenes_multi_proveedor" }, itemCatalog = { propose: async (description: string) => { const key = description.toLocaleLowerCase(); const existing = proposed.get(key); if (existing) return { id: existing, created: false }; const id = `catalog-${++seq}`; proposed.set(key, id); return { id, created: true }; } }, notifications = { enqueue: async (notification: (typeof notificationData)[number]) => { notificationData.push(notification); } };
  const pettyCash = { save: async (p: PettyCash) => { petty.push(p); const generated: Expense = { id: `expense-${p.id}`, workId: p.workId, origin: "caja_menor", referenceId: p.id, tagId: p.tagId, date: p.date, base: p.amount, iva: 0, total: p.amount, period: p.date.slice(0, 7) }; expensesData.push(generated); return generated; }, list: async () => petty }, catalogs = { create: async (_kind: string, value: never) => value, get: async () => null, update: async (_kind: string, _id: string, value: never) => value, findSupplierDuplicate: async () => null, isEligibleApprover: async () => true };
  const transactions = { transaction: async <T>(_id: string | undefined, work: (repositories: Parameters<ServiceDependencies["transactions"]["transaction"]>[1] extends (repositories: infer R) => Promise<unknown> ? R : never) => Promise<T>) => {
    const snapshot = { req: structuredClone([...req.entries()]), orders: structuredClone(ordersData), expenses: structuredClone(expensesData), petty: structuredClone(petty), audits: structuredClone(audits), shares: structuredClone(shares), proposed: structuredClone([...proposed.entries()]), notifications: structuredClone(notificationData) };
    try { return await work({ requisitions, orders, expenses, pettyCash, audit, consecutives, tags, features, items: itemCatalog, catalogs, notifications }); }
    catch (error) { req.clear(); for (const [id, value] of snapshot.req) req.set(id, value); ordersData.splice(0, ordersData.length, ...snapshot.orders); expensesData.splice(0, expensesData.length, ...snapshot.expenses); petty.splice(0, petty.length, ...snapshot.petty); audits.splice(0, audits.length, ...snapshot.audits); shares.splice(0, shares.length, ...snapshot.shares); proposed.clear(); for (const [key, value] of snapshot.proposed) proposed.set(key, value); notificationData.splice(0, notificationData.length, ...snapshot.notifications); throw error; }
  } };
  return { req, ordersData, expensesData, pettyData: petty, proposedItems: proposed, notificationData, audits, shares, visibleActors, transactionCalls: 0, ids: { next: () => `id-${++seq}` }, clock: { now: () => new Date("2026-08-24T12:00:00.000Z") }, consecutives, publicAccess: { verify: async (workId, token, code) => workId === "work" && token === "link" && code === "1234" }, tags, features, items: itemCatalog, catalogs, notifications, transactions, requisitions, orders, expenses, pettyCash, audit };
}
const reviewer = { actor: { id: "daniel", roles: ["revisor"] as const } }, approver = { actor: { id: "nelson", roles: ["aprobador"] as const } }, requester = { actor: { id: "sol", roles: ["solicitante"] as const } };
const items = [{ id: "l1", itemId: "catalog-cemento", description: "Cemento", quantity: 2, unit: "und", unitBase: 100, unitIva: 19, unitTotal: 119, finalSupplierId: "p1" }, { id: "l2", itemId: "catalog-arena", description: "Arena", quantity: 1, unit: "und", unitBase: 200, unitIva: 38, unitTotal: 238, finalSupplierId: "p2" }];
async function reviewed(service: ProcurementService) { const r = await service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items }, requester); await service.startReview(r.id, reviewer); await service.review(r.id, { tagId: "tag", items }, reviewer); return service.sendForApproval(r.id, reviewer); }

describe("ProcurementService", () => {
  it("persists enviada first and enters review through an audited explicit transition", async () => { const deps = fakeDeps(), service = new ProcurementService(deps); const r = await service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items }, requester); expect(r.status).toBe("enviada"); expect(deps.audits.map((a) => a.event)).toEqual(["creada"]); await service.startReview(r.id, reviewer); expect((await deps.requisitions.get(r.id))?.status).toBe("en_revision"); expect(deps.audits.at(-1)?.data).toMatchObject({ from: "enviada", to: "en_revision" }); });
  it("uses a verifier for public access, materializes proposals and requires external identity", async () => { const deps = fakeDeps(), service = new ProcurementService(deps); const created = await service.create({ type: "pago", workId: "work", requiredDate: "2026-08-30", channel: "publico", publicCode: "1234", publicLinkToken: "link", externalRequester: { name: "Maestro", phone: "+57 300 123 4567" }, items: [{ ...items[0], itemId: undefined, description: "Tubería especial" }] }, {}); expect(created).toMatchObject({ status: "enviada", externalRequester: { phone: "+573001234567" }, items: [{ itemId: expect.stringMatching(/^catalog-/) }] }); expect(deps.audits.map((entry) => entry.event)).toContain("propuesto"); await expect(service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "publico", publicCode: "1234", publicLinkToken: "link", externalRequester: { name: "Maestro" }, items }, {})).rejects.toMatchObject({ code: "INVALID_INPUT" }); });
  it("routes from tag data, does not accept client approver, and audits return transitions", async () => { const service = new ProcurementService(fakeDeps()), r = await service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items }, requester); await service.startReview(r.id, reviewer); const reviewedR = await service.review(r.id, { tagId: "tag", items }, reviewer); expect(reviewedR.approverId).toBe("nelson"); await expect(service.review(r.id, { tagId: "missing", items }, reviewer)).rejects.toMatchObject({ code: "ROUTING_NOT_FOUND" }); await service.sendForApproval(r.id, reviewer); await expect(service.returnForCorrection(r.id, "", approver)).rejects.toBeInstanceOf(DomainError); expect((await service.returnForCorrection(r.id, "falta soporte", approver)).status).toBe("devuelta"); });
  it("returns traceability only after applying requisition visibility", async () => { const service = new ProcurementService(fakeDeps()), r = await service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items }, requester); await service.startReview(r.id, reviewer); const history = await service.getRequisitionHistory(r.id, reviewer); expect(history.map((entry) => entry.event)).toEqual(["creada", "entrada_revision"]); await expect(service.getRequisitionHistory(r.id, { actor: { id: "stranger", roles: ["solicitante"] } })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("does not let an MCP caller bypass service read permissions", async () => { const service = new ProcurementService(fakeDeps()); await expect(service.listOrders({ ...requester, origin: "mcp" })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(service.listExpenses({ ...requester, origin: "mcp" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("approves transactionally and idempotently, making one expense per supplier order", async () => { const deps = fakeDeps(), service = new ProcurementService(deps), r = await reviewed(service), originalTransaction = deps.transactions.transaction; let calls = 0, transactionalReposUsed = false; deps.transactions.transaction = async (lockedId, work) => { calls++; expect(lockedId).toBe(`requisition:${r.id}`); return originalTransaction(lockedId, async (repositories) => work({ ...repositories, requisitions: { ...repositories.requisitions, get: async (id) => { transactionalReposUsed = true; return repositories.requisitions.get(id); } } })); }; const first = await service.approve(r.id, approver, true); const second = await service.approve(r.id, approver, true); expect(calls).toBe(2); expect(transactionalReposUsed).toBe(true); expect(first.orders).toHaveLength(2); expect(second.orders).toHaveLength(2); expect(deps.ordersData).toHaveLength(2); expect(deps.expensesData).toHaveLength(2); expect(deps.expensesData.map((e) => e.supplierId).sort()).toEqual(["p1", "p2"]); expect(deps.notificationData.filter((entry) => entry.template === "requisicion_aprobada")).toHaveLength(1); expect(deps.audits.map((a) => a.entity)).toContain("orden"); expect(deps.audits.map((a) => a.entity)).toContain("gasto"); await expect(service.approve(r.id, { actor: { id: "other", roles: ["aprobador"] } })).rejects.toMatchObject({ code: "NOT_ASSIGNED_APPROVER" }); });
  it("rejects incomplete review or a disabled Complete gate and blocks approval in MCP", async () => { const service = new ProcurementService(fakeDeps()), r = await reviewed(service); await expect(service.approve(r.id, { ...approver, origin: "mcp" }, true)).rejects.toMatchObject({ code: "FORBIDDEN" }); const unassigned = new ProcurementService(fakeDeps()); const req = await unassigned.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items: [{ ...items[0], finalSupplierId: undefined }] }, requester); await unassigned.startReview(req.id, reviewer); await unassigned.review(req.id, { tagId: "tag", items: [{ ...items[0], finalSupplierId: undefined }] }, reviewer); await expect(unassigned.sendForApproval(req.id, reviewer)).rejects.toMatchObject({ code: "REVIEW_INCOMPLETE" }); const zeroQuote = new ProcurementService(fakeDeps()), zero = await zeroQuote.create({ type: "pago", workId: "work", requiredDate: "2026-08-30", channel: "web", items: [{ ...items[0], unitBase: 0, unitIva: 0, unitTotal: 0 }] }, requester); await zeroQuote.startReview(zero.id, reviewer); await zeroQuote.review(zero.id, { tagId: "tag", items: [{ ...items[0], unitBase: 0, unitIva: 0, unitTotal: 0 }] }, reviewer); await expect(zeroQuote.sendForApproval(zero.id, reviewer)).rejects.toMatchObject({ code: "REVIEW_INCOMPLETE" }); const gatedDeps = fakeDeps(), gatedService = new ProcurementService(gatedDeps), gated = await reviewed(gatedService); gatedDeps.features.isEnabled = async () => false; await expect(gatedService.approve(gated.id, approver, true)).rejects.toMatchObject({ code: "FEATURE_DISABLED" }); });
  it("enforces shares, order fulfillment, role-scoped dashboard, typed failures and unit totals", async () => { const deps = fakeDeps(), service = new ProcurementService(deps), r = await reviewed(service); const approved = await service.approve(r.id, approver, true); expect(approved.expenses.reduce((sum, expense) => sum + expense.total, 0)).toBe(476); await expect(service.redistribute("e", 100, [{ expenseId: "wrong", workId: "a", amount: 100 }], reviewer)).rejects.toMatchObject({ code: "INVALID_SHARE" }); await expect(service.redistribute("missing", 100, [{ expenseId: "missing", workId: "a", amount: 100 }], reviewer)).rejects.toMatchObject({ code: "NOT_FOUND" }); await expect(service.redistribute(approved.expenses[0].id, 999, [{ expenseId: approved.expenses[0].id, workId: "a", amount: 999 }], reviewer)).rejects.toMatchObject({ code: "EXPENSE_TOTAL_MISMATCH" }); await service.redistribute(approved.expenses[0].id, approved.expenses[0].total, [{ expenseId: approved.expenses[0].id, workId: "a", amount: approved.expenses[0].total }], reviewer); await expect(service.updateOrderStatus(approved.orders[0].id, "cumplida", reviewer)).resolves.toMatchObject({ status: "cumplida" }); await expect(service.updateOrderStatus(approved.orders[0].id, "no_cumplida", reviewer)).rejects.toMatchObject({ code: "INVALID_TRANSITION" }); const cash = await service.registerPettyCash({ workId: "work", date: "2026-08-03", concept: "Taxi", tagId: "t", amount: 500 }, reviewer); expect(cash.expense.origin).toBe("caja_menor"); await expect(service.dashboard("2026-08", reviewer)).resolves.toMatchObject({ periodExpense: 976 }); expect(deps.visibleActors).toEqual(expect.arrayContaining(["req:daniel", "order:daniel", "expense:daniel"])); const approverDashboard = await service.dashboard("2026-08", approver); expect(approverDashboard.byStatus.aprobada).toBe(1); expect(deps.visibleActors).toEqual(expect.arrayContaining(["req:nelson", "order:nelson", "expense:nelson"])); const ownDashboard = await service.dashboard("2026-08", requester); expect(ownDashboard.byStatus.en_revision).toBe(0); expect(deps.visibleActors).toEqual(expect.arrayContaining(["req:sol", "order:sol", "expense:sol"])); await expect(service.dashboard("bad", reviewer)).rejects.toMatchObject({ code: "INVALID_INPUT" }); await expect(service.startReview("missing", reviewer)).rejects.toMatchObject({ code: "NOT_FOUND" }); expect(service.lineTotal(items[0])).toBe(238); });
  it("declines a requisition with an audited reason, notifies the requester and never generates orders or expenses", async () => {
    // RF-304/PRD §5.2/§3.2: "declinada... nunca genera gasto". decline() no tenía ninguna prueba en ningún nivel.
    const deps = fakeDeps(), service = new ProcurementService(deps), r = await service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items }, requester);
    await service.startReview(r.id, reviewer);
    await expect(service.decline(r.id, "", reviewer)).rejects.toMatchObject({ code: "COMMENT_REQUIRED" });
    const declined = await service.decline(r.id, "motivo", reviewer);
    expect(declined.status).toBe("declinada"); expect(declined.declineReason).toBe("motivo");
    expect(deps.audits.map((a) => a.event)).toContain("declinada");
    expect(deps.audits.find((a) => a.event === "declinada")?.data).toMatchObject({ from: "en_revision", to: "declinada", comment: "motivo" });
    expect(deps.notificationData.map((n) => n.template)).toContain("requisicion_declinada");
    expect(deps.ordersData).toHaveLength(0); expect(deps.expensesData).toHaveLength(0);
    // Una vez declinada, es un estado terminal: no admite volver a decline ni ninguna otra transición.
    await expect(service.decline(r.id, "otra vez", reviewer)).rejects.toMatchObject({ code: "INVALID_TRANSITION" });
  });
  it("generates a single OP with one expense end-to-end on the payment-order success path", async () => {
    // RF-501/502: groupOrderItems(..., "pago") nunca se ejecutaba por su camino de éxito en toda la suite.
    // Un solo proveedor final evita MULTI_SUPPLIER_PAYMENT y ejercita approve() completo para type:"pago".
    const deps = fakeDeps(), service = new ProcurementService(deps), paymentItems = [items[0]];
    const r = await service.create({ type: "pago", workId: "work", requiredDate: "2026-08-30", channel: "web", items: paymentItems }, requester);
    await service.startReview(r.id, reviewer);
    await service.review(r.id, { tagId: "tag", items: paymentItems }, reviewer);
    await service.sendForApproval(r.id, reviewer);
    const { orders, expenses } = await service.approve(r.id, approver);
    expect(orders).toHaveLength(1); expect(orders[0]).toMatchObject({ type: "OP", supplierId: "p1" }); expect(orders[0].consecutive).toMatch(/^OP-2026-\d{4}$/);
    expect(expenses).toHaveLength(1); expect(expenses[0].total).toBe(238);
  });
  it("restricts item proposals by owner, review state and supports reviewer creation on behalf", async () => { const service = new ProcurementService(fakeDeps()), r = await service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items }, requester); await expect(service.proposeItem(r.id, "ajeno", { actor: { id: "other", roles: ["solicitante"] } })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(service.proposeItem(r.id, "propio", requester)).resolves.toMatchObject({ items: expect.any(Array) }); await service.startReview(r.id, reviewer); await expect(service.proposeItem(r.id, "tarde", requester)).rejects.toMatchObject({ code: "INVALID_STATE" }); await expect(service.proposeItem(r.id, "Daniel", reviewer)).resolves.toMatchObject({ items: expect.any(Array) }); await expect(service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", requesterId: "other", items }, requester)).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", requesterId: "sol", externalRequester: { name: "no" }, items }, requester)).rejects.toMatchObject({ code: "INVALID_INPUT" }); await expect(service.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", requesterId: "maestro", items }, reviewer)).resolves.toMatchObject({ requesterId: "maestro" }); });
  it("rolls back the complete unit of work when a downstream write fails", async () => {
    const createDeps = fakeDeps(), createService = new ProcurementService(createDeps);
    createDeps.audit.append = async () => { throw new Error("audit unavailable"); };
    await expect(createService.create({ type: "compra", workId: "work", requiredDate: "2026-08-30", channel: "web", items: [{ ...items[0], itemId: undefined, description: "Propuesta que debe revertirse" }] }, requester)).rejects.toThrow("audit unavailable");
    expect(createDeps.req.size).toBe(0);
    expect(createDeps.proposedItems.size).toBe(0);

    const cashDeps = fakeDeps(), cashService = new ProcurementService(cashDeps);
    cashDeps.pettyCash.save = async (entry) => { cashDeps.pettyData.push(entry); throw new Error("expense unavailable"); };
    await expect(cashService.registerPettyCash({ workId: "work", date: "2026-08-03", concept: "Taxi", tagId: "tag", amount: 500 }, reviewer)).rejects.toThrow("expense unavailable");
    expect(cashDeps.pettyData).toHaveLength(0);
    expect(cashDeps.expensesData).toHaveLength(0);

    const approvalDeps = fakeDeps(), approvalService = new ProcurementService(approvalDeps), r = await reviewed(approvalService);
    approvalDeps.notifications.enqueue = async () => { throw new Error("notification unavailable"); };
    await expect(approvalService.approve(r.id, approver, true)).rejects.toThrow("notification unavailable");
    expect((await approvalDeps.requisitions.get(r.id))?.status).toBe("en_aprobacion");
    expect(approvalDeps.ordersData).toHaveLength(0);
    expect(approvalDeps.expensesData).toHaveLength(0);
    expect(approvalDeps.notificationData).toHaveLength(1);
    expect(approvalDeps.audits.some((entry) => entry.event === "aprobada")).toBe(false);
  });
});
